<?xml  version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple Computer//DTD PLIST 1.0//EN"   "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0" >
<!-- Generated via Iro -->
<dict>
  <key>fileTypes</key>
  <array> 
    <string>mu</string>
   </array>
  <key>name</key>
  <string>MUSH</string>
  <key>patterns</key>
  <array> 
    <dict>
      <key>include</key>
      <string>#main</string>
    </dict>
   </array>
  <key>scopeName</key>
  <string>source.MUSH</string>
  <key>uuid</key>
  <string></string>
  <key>repository</key>
  <dict>
    <key>main</key>
    <dict>
      <key>patterns</key>
      <array> 
        <dict>
          <key>match</key>
          <string>(%[a-zA-Z0-9\x{0023}\x{0021}\x{007c}]+)</string>
          <key>name</key>
          <string>variable.MUSH</string>
        </dict>
        <dict>
          <key>match</key>
          <string>([\x{003d}\x{003b}\x{002c}])</string>
          <key>name</key>
          <string>entity.name.section.MUSH</string>
        </dict>
        <dict>
          <key>match</key>
          <string>([\x{0040}\x{0026}\x{002b}]\.?\w+)</string>
          <key>name</key>
          <string>keyword.MUSH</string>
        </dict>
        <dict>
          <key>include</key>
          <string>#comments</string>
        </dict>
        <dict>
          <key>include</key>
          <string>#brackets</string>
        </dict>
        <dict>
          <key>include</key>
          <string>#parens</string>
        </dict>
        <dict>
          <key>include</key>
          <string>#meta</string>
        </dict>
       </array>
    </dict>
    <key>brackets</key>
    <dict>
      <key>patterns</key>
      <array> 
        <dict>
          <key>begin</key>
          <string>(\[)</string>
          <key>beginCaptures</key>
          <dict>
            <key>1</key>
            <dict>
              <key>name</key>
              <string>entity.name.tag.MUSH</string>
            </dict>
          </dict>
          <key>patterns</key>
          <array> 
            <dict>
              <key>include</key>
              <string>#brackets__1</string>
            </dict>
           </array>
          <key>end</key>
          <string>(\])</string>
          <key>endCaptures</key>
          <dict>
            <key>1</key>
            <dict>
              <key>name</key>
              <string>entity.name.tag.MUSH</string>
            </dict>
          </dict>
        </dict>
        <dict>
          <key>match</key>
          <string>(\])</string>
          <key>name</key>
          <string>invalid.MUSH</string>
        </dict>
       </array>
    </dict>
    <key>brackets__1</key>
    <dict>
      <key>patterns</key>
      <array> 
        <dict>
          <key>include</key>
          <string>#main</string>
        </dict>
       </array>
    </dict>
    <key>comments</key>
    <dict>
      <key>patterns</key>
      <array> 
        <dict>
          <key>match</key>
          <string>(//.*)</string>
          <key>name</key>
          <string>comment.MUSH</string>
        </dict>
        <dict>
          <key>begin</key>
          <string>(/\*)</string>
          <key>beginCaptures</key>
          <dict>
            <key>1</key>
            <dict>
              <key>name</key>
              <string>comment.MUSH</string>
            </dict>
          </dict>
          <key>contentName</key>
          <string>comment.MUSH</string>
          <key>end</key>
          <string>(\*/)</string>
          <key>endCaptures</key>
          <dict>
            <key>1</key>
            <dict>
              <key>name</key>
              <string>comment.MUSH</string>
            </dict>
          </dict>
        </dict>
       </array>
    </dict>
    <key>comments__1</key>
    <dict>
      <key>patterns</key>
      <array> 
       </array>
    </dict>
    <key>meta</key>
    <dict>
      <key>patterns</key>
      <array> 
        <dict>
          <key>begin</key>
          <string>(^#.*)</string>
          <key>beginCaptures</key>
          <dict>
            <key>1</key>
            <dict>
              <key>name</key>
              <string>meta.MUSH</string>
            </dict>
          </dict>
          <key>patterns</key>
          <array> 
            <dict>
              <key>include</key>
              <string>#meta__1</string>
            </dict>
           </array>
          <key>end</key>
          <string>(\})</string>
          <key>endCaptures</key>
          <dict>
            <key>1</key>
            <dict>
              <key>name</key>
              <string>meta.MUSH</string>
            </dict>
          </dict>
        </dict>
        <dict>
          <key>match</key>
          <string>(\})</string>
          <key>name</key>
          <string>invalid.MUSH</string>
        </dict>
       </array>
    </dict>
    <key>meta__1</key>
    <dict>
      <key>patterns</key>
      <array> 
        <dict>
          <key>include</key>
          <string>#main</string>
        </dict>
       </array>
    </dict>
    <key>parens</key>
    <dict>
      <key>patterns</key>
      <array> 
        <dict>
          <key>begin</key>
          <string>(\()</string>
          <key>beginCaptures</key>
          <dict>
            <key>1</key>
            <dict>
              <key>name</key>
              <string>support.function.MUSH</string>
            </dict>
          </dict>
          <key>patterns</key>
          <array> 
            <dict>
              <key>include</key>
              <string>#parens__1</string>
            </dict>
           </array>
          <key>end</key>
          <string>(\))</string>
          <key>endCaptures</key>
          <dict>
            <key>1</key>
            <dict>
              <key>name</key>
              <string>support.function.MUSH</string>
            </dict>
          </dict>
        </dict>
        <dict>
          <key>match</key>
          <string>(\))</string>
          <key>name</key>
          <string>invalid.MUSH</string>
        </dict>
       </array>
    </dict>
    <key>parens__1</key>
    <dict>
      <key>patterns</key>
      <array> 
        <dict>
          <key>include</key>
          <string>#main</string>
        </dict>
       </array>
    </dict>
  </dict>
</dict>
</plist>
